# Generated by Django 4.1.5 on 2023-01-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snacks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snack",
            name="image_url",
            field=models.URLField(default="none"),
        ),
    ]
